name: Tests

on:
  push:
    branches:
      - 'main'
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        shell: ["powershell","pwsh","cmd"]
    runs-on: windows-latest
    defaults:
      run:
        shell: ${{ matrix.shell }}
    steps:
      - name: Checkout Bucket
        uses: actions/checkout@main
      - name: Build package
        run: |
          choco pack
      - name: Install Package
        run: |
          choco install pact --debug --verbose --source .
      - name: Test scripts
        run: |
          cd C:\
          pact.bat --help
          pact-broker.bat --help
          pact-message.bat --help
          pact-mock-service.bat --help
          pact-plugin-cli.exe --help
          pact-provider-verifier.bat --help
          pact-stub-service.bat --help
          pactflow.bat --help
          pact_mock_server_cli.exe --help
          pact_verifier_cli.exe --help