name: Tests

on:
  push:
    branches:
      - 'main'
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        shell: [
          "powershell",
          # "pwsh",
          "cmd"
          ]
        os: [
          "windows-latest",
          "windows-11-arm"
          ]
        package: [
          "pact-legacy",
          "pact",
          "pact-plugin",
          "pact-verifier",
          "pact-stub-server",
          "pact-mock-server",
          "pact-broker-client"
          ]
    defaults:
      run:
        shell: ${{ matrix.shell }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Bucket
        uses: actions/checkout@main
      - name: Build ${{ matrix.package }} Package
        run: |
          choco pack .\${{ matrix.package }}.nuspec
      - name: Install ${{ matrix.package }} Package
        if: matrix.os != 'windows-11-arm'
        run: |
          choco install ${{ matrix.package }} --debug --verbose --source .
      - name: Install ${{ matrix.package }} Package
        if: matrix.os == 'windows-11-arm'
        run: | # explicitly force ARM64 install via --params "'/ForceARM64:true'" as choco does not have native ARM64 detection
          choco install ${{ matrix.package }} --debug --verbose --source . --params "'/ForceARM64:true'"
      - name: Test pact-legacy scripts
        if: matrix.package == 'pact-legacy'
        run: |
          cd C:\
          pact-broker --help
          pact-message --help
          pact-mock-service --help
          pact-provider-verifier --help
          pact-stub-service --help
          pactflow --help
      - name: Test ${{ matrix.package }} scripts
        if: matrix.package != 'pact-legacy'
        run: |
          ${{ matrix.package }} --help
      - name: Uninstall ${{ matrix.package }} Package
        run: |
          choco uninstall ${{ matrix.package }}