name: Tests

on:
  push:
    branches:
      - 'main'
      - 'master'
      - 'test'
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        shell: ["powershell","pwsh","cmd"]
    runs-on: windows-latest
    defaults:
      run:
        shell: ${{ matrix.shell }}
    steps:
      - name: Checkout Bucket
        uses: actions/checkout@main
      - name: Build package
        run: |
          choco pack
      - name: Install Package
        run: |
          choco install pact --debug --verbose --source .
      - name: Test scripts
        run: |
          .\\pact\\bin\\pact.bat
          .\\pact\\bin\\pact-broker.bat --help
          .\\pact\\bin\\pact-message.bat --help
          .\\pact\\bin\\pact-mock-service.bat --help
          .\\pact\\bin\\pact-plugin-cli.exe --help
          .\\pact\\bin\\pact-provider-verifier.bat --help
          .\\pact\\bin\\pact-stub-service.bat --help
          .\\pact\\bin\\pactflow.bat --help