name: Tests

on:
  push:
    branches:
      - 'main'
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        shell: ["powershell","pwsh","cmd"]
        os: ["windows-latest"]
        package: ["pact-legacy"]
    defaults:
      run:
        shell: ${{ matrix.shell }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Bucket
        uses: actions/checkout@main
      - name: Build ${{ matrix.package }} Package
        run: |
          choco pack .\${{ matrix.package }}.nuspec
      - name: Install ${{ matrix.package }} Package
        run: |
          choco install ${{ matrix.package }} --debug --verbose --source .
      - name: Test scripts
        if: matrix.package == 'pact-legacy'
        run: |
          cd C:\
          pact-broker.bat --help
          pact-message.bat --help
          pact-mock-service.bat --help
          pact-plugin-cli.exe --help
          pact-provider-verifier.bat --help
          pact-stub-service.bat --help
          pactflow.bat --help
      - name: Uninstall ${{ matrix.package }} Package
        run: |
          choco uninstall ${{ matrix.package }}