name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'SemVer format release tag, i.e. 0.24.5'
        required: true
  repository_dispatch:
    types: [ bump-chocolatey ]
jobs:
  get-version:
    name: Get Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Get version
        id: get_version
        run: |
          if [ "${{ github.event_name }}" == "repository_dispatch" ]
          then
            echo "version=${{ github.event.client_payload.version }}" >> $GITHUB_OUTPUT
          else
            echo "version=${{ inputs.version }}" >> $GITHUB_OUTPUT
          fi
  release:
    needs: get-version
    runs-on: windows-latest
    steps:
      - name: Checkout Bucket
        uses: actions/checkout@main
      - run: choco pack
      - run: choco install pact --debug --verbose --source .
      - name: Test scripts
        run: |
          cd C:\
          pact.bat --help
          pact-broker.bat --help
          pact-message.bat --help
          pact-mock-service.bat --help
          pact-plugin-cli.exe --help
          pact-provider-verifier.bat --help
          pact-stub-service.bat --help
          pactflow.bat --help
          pact_mock_server_cli.exe --help
          pact_verifier_cli.exe --help
      - run: choco uninstall pact
      - name: auth with choco registry
        run: choco apikey --key ${{ secrets.CHOCO_API_KEY }} --source https://push.chocolatey.org/
      - name: push package
        run: |
          choco push pact.${{ needs.get-version.outputs.version }}.nupkg --source https://push.chocolatey.org/
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "pact.${{ needs.get-version.outputs.version }}.nupkg"
          tag: pact-${{ needs.get-version.outputs.version }}
  smoke-test:
    needs: release
    runs-on: windows-latest
    steps:
      - run: choco install pact --debug --verbose --version=${{ needs.get-version.outputs.version }}
      - name: Test scripts
        run: |
          cd C:\
          pact.bat --help
          pact-broker.bat --help
          pact-message.bat --help
          pact-mock-service.bat --help
          pact-plugin-cli.exe --help
          pact-provider-verifier.bat --help
          pact-stub-service.bat --help
          pactflow.bat --help
          pact_mock_server_cli.exe --help
          pact_verifier_cli.exe --help