name: smoke-test

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'SemVer format release tag, i.e. 0.24.5'
        required: true
  repository_dispatch:
    types: [ chocolatey-package-released ]
jobs:
  get-version:
    name: Get Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Get version
        id: get_version
        run: |
          if [ "${{ github.event_name }}" == "repository_dispatch" ]
          then
            echo "version=${{ github.event.client_payload.version }}" >> $GITHUB_OUTPUT
          else
            echo "version=${{ inputs.version }}" >> $GITHUB_OUTPUT
          fi
  smoke-test:
    needs: get-version
    runs-on: windows-latest
    steps:
      - run: choco install pact-legacy --debug --verbose --version=${{ needs.get-version.outputs.version }}
      - name: Test scripts
        run: |
          cd C:\
          pact-broker.bat --help
          pact-message.bat --help
          pact-mock-service.bat --help
          pact-provider-verifier.bat --help
          pact-stub-service.bat --help
          pactflow.bat --help